#!/bin/bash
# Quick Test Script for Agent Creation and Download
# Run this after creating an agent in the NOP UI

echo "=== NOP Agent Test Guide ==="
echo ""
echo "1. CREATE AGENT IN UI:"
echo "   - Open http://localhost:12000/agents"
echo "   - Click '+ Create Agent'"
echo "   - Fill in:"
echo "     * Name: Test Agent 1"
echo "     * Type: Python"
echo "     * Connection URL: Use 'Local IP' option"
echo "   - Click 'Create Agent'"
echo "   - Agent file should download automatically"
echo ""
echo "2. GET DOWNLOAD TOKEN:"
echo "   - Look at the agent card in UI"
echo "   - Find 'Download Link' section"
echo "   - Copy the token (last part of URL)"
echo "   - Example: If link is '/api/v1/agents/download/abc123...'"
echo "   - Token is: abc123..."
echo ""
echo "3. DOWNLOAD TO TEST HOST:"
echo "   docker exec -it nop-agent-test bash"
echo "   cd /opt/agents"
echo "   ./download-agent.sh <YOUR_TOKEN>"
echo ""
echo "4. RUN THE AGENT:"
echo "   python3 /opt/agents/agent.py"
echo ""
echo "5. VERIFY IN UI:"
echo "   - Agent status should change from 'OFFLINE' to 'CONNECTED'"
echo "   - Green indicator should appear"
echo ""
echo "=== Test Host Info ==="
echo "Container: nop-agent-test"
echo "NOP Network IP: 172.28.0.100"
echo "Test Network IP: 172.21.0.100"
echo "Python: $(docker exec nop-agent-test python3 --version)"
echo ""
echo "=== Access Test Host ==="
echo "docker exec -it nop-agent-test bash"
echo ""
